name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 0
    - name: 'Git Fetch Tags'
      run: git fetch --tags
      shell: pwsh
    - name: 'Install .NET Core SDK'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: 'Dotnet Tool Restore'
      run: dotnet tool restore
      shell: pwsh
    - name: 'Dotnet Cake Build'
      run: dotnet cake --target=Build
      shell: pwsh
    - name: 'Dotnet Cake Test'
      run: dotnet cake --target=Test
      shell: pwsh
    - name: 'Dotnet Cake Pack'
      run: dotnet cake --target=Pack
      shell: pwsh
    - name: 'Dotnet Cacke Publish'
      run: dotnet cake --target=Publish
      shell: pwsh
    - name: 'Publish Packages (nupkg)'
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: './Artefacts/*.nupkg;'
    - name: 'Publish Packages (snupkg)'
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: './Artefacts/*.snupkg;'
    - name: 'Publish Code Coverage'
      uses: actions/upload-artifact@v2
      with:
        name: tests
        path: './Artefacts/**/coverage.opencover.xml'
    - name: 'Publish Test Results'
      uses: actions/upload-artifact@v2
      with:
        name: tests
        path: './Artefacts/Witness.Test.html'